const CARGOS_PERSONAL = [
  'Entrenador',
  '2º ENTRENADOR',
  'PREP. FÍSISCO',
  'ANALISTA',
  'PSICOLOGO',
  'PRESIDENTE',
  'DIRECTOR GENERAL',
  'RESP CAPTACIÓN',
  'COORDONADOR INF',
  'COORDINADOR ALV- BENJ',
  'COORDINADOR FEDERADO',
];

module.exports = { CARGOS_PERSONAL };
